#!/bin/bash

link_src () {
	bot_retorno="$LINE\n"
	bot_retorno+="sudo apt update -y; apt upgrade -y; wget -q https://www.dropbox.com/s/bs28yq7u0ikv04g/instala.sh; chmod +x instala.sh;./instala.sh\n"
	bot_retorno+="$LINE\n"
msj_fun
}
